foreground   #f5dfb0
background   #0a1419
cursor       #f5dfb0

color0       #0a1419
color8       #ab9c7b
color1       #A05651
color9       #A05651
color2       #D85D4C
color10      #D85D4C
color3       #F16F4F
color11      #F16F4F
color4       #DC9532
color12      #DC9532
color5       #FA8E53
color13      #FA8E53
color6       #F8AA62
color14      #F8AA62
color7       #f5dfb0
color15      #f5dfb0
