font_family JetBrainsMonoNL NFM ExtraLight 
bold_font JetBrainsMonoNL NFM Bold
italic_font JetBrainsMonoNL NFM Italic
bold_italic_font JetBrainsMonoNL NFM Bold Italic
font_size 14.0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
wayland_titlebar_color #1d2021


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
# background #0f111a
