# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

linux_display_server x11

font_family JetBrainsMonoNL Nerd Font Mono
bold_font JetBrainsMonoNL NFM Bold
italic_font JetBrainsMonoNL NFM Italic
bold_italic_font JetBrainsMonoNL NFM Bold Italic
font_size 14.0

map ctrl+plus change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
