font_family JetBrainsMonoNL Nerd Font Mono
bold_font JetBrainsMonoNL NFM Bold
italic_font JetBrainsMonoNL NFM Italic
bold_italic_font JetBrainsMonoNL NFM Bold Italic
font_size 14.0
map ctrl+plus change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

include Gruvbox Dark Hard.conf
background #1a1220
background_opacity 0.97
wayland_titlebar_color background
