vim.g.mapleader = " "

vim.keymap.set("n", "<leader>wh", vim.cmd.new)
vim.keymap.set("n", "<leader>wv", vim.cmd.vne)

vim.keymap.set("n", "<leader><left>", function()
    vim.cmd("wincmd h")
end)
vim.keymap.set("n", "<leader>h", function()
    vim.cmd("wincmd h")
end)
vim.keymap.set("n", "<leader><right>", function()
    vim.cmd("wincmd l")
end)
vim.keymap.set("n", "<leader>l", function()
    vim.cmd("wincmd l")
end)
vim.keymap.set("n", "<leader><up>", function()
    vim.cmd("wincmd k")
end)
vim.keymap.set("n", "<leader>k", function()
    vim.cmd("wincmd k")
end)
vim.keymap.set("n", "<leader><down>", function()
    vim.cmd("wincmd j")
end)
vim.keymap.set("n", "<leader>j", function()
    vim.cmd("wincmd j")
end)
